# Generated by Django 4.2.3 on 2023-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_member',
            },
        ),
    ]
