# Generated by Django 4.2.3 on 2023-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_password',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
