# Generated by Django 4.2.3 on 2023-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.BooleanField(default=True),
        ),
    ]
