# Generated by Django 4.2.3 on 2023-08-01 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_member_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
