# Generated by Django 4.2.3 on 2023-08-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_create_date_member_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
    ]
