# Generated by Django 4.2.3 on 2023-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_status',
            field=models.CharField(choices=[('Y', '일반 댓글'), ('N', '비밀 댓글')], default='Y', max_length=1),
        ),
    ]
