# Generated by Django 4.2.3 on 2023-08-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0011_alter_member_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'seq_pay',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('pay_status', models.CharField(choices=[('Done', '결제 완료'), ('Cancel', '결제 취소')], default='Done', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
            options={
                'db_table': 'tbl_pay',
                'ordering': ['-create_date'],
            },
        ),
    ]
