# Generated by Django 4.2.3 on 2023-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='create_date',
            field=models.DateField(default='2023-08-04'),
            preserve_default=False,
        ),
    ]
