# Generated by Django 4.2.3 on 2023-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_sequence_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pay',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
