# Generated by Django 4.2.4 on 2023-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_test', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
